#!/usr/bin/env python3
import json
import os
import argparse
from pathlib import Path

STATE_DIR = Path("workflows")

def load_state(assignment_id):
    file_path = STATE_DIR / f"{assignment_id}.json"
    if not file_path.exists():
        return None
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_state(state):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    file_path = STATE_DIR / f"{state['assignment_id']}.json"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)
    return str(file_path)

def init_assignment(assignment_id, objective):
    state = {
        "assignment_id": assignment_id,
        "objective": objective,
        "status": "planning",
        "tasks": []
    }
    save_state(state)
    print(f"Initialized assignment {assignment_id}")

def add_task(assignment_id, task_id, description, assigned_agent, dependencies=None):
    state = load_state(assignment_id)
    if not state:
        print(f"Error: Assignment {assignment_id} not found.")
        return
    
    deps = dependencies.split(",") if dependencies else []
    
    task = {
        "task_id": task_id,
        "description": description,
        "assigned_agent": assigned_agent,
        "status": "pending",
        "dependencies": deps,
        "output_file": ""
    }
    
    # Check if task already exists
    for i, t in enumerate(state["tasks"]):
        if t["task_id"] == task_id:
            state["tasks"][i] = task
            save_state(state)
            print(f"Updated task {task_id} in {assignment_id}")
            return
            
    state["tasks"].append(task)
    save_state(state)
    print(f"Added task {task_id} to {assignment_id}")

def update_task_status(assignment_id, task_id, status, output_file=None):
    state = load_state(assignment_id)
    if not state:
        print(f"Error: Assignment {assignment_id} not found.")
        return
        
    for task in state["tasks"]:
        if task["task_id"] == task_id:
            task["status"] = status
            if output_file:
                task["output_file"] = output_file
            save_state(state)
            print(f"Updated task {task_id} status to {status}")
            return
            
    print(f"Error: Task {task_id} not found.")

def update_assignment_status(assignment_id, status):
    state = load_state(assignment_id)
    if not state:
        print(f"Error: Assignment {assignment_id} not found.")
        return
    
    state["status"] = status
    save_state(state)
    print(f"Updated assignment {assignment_id} status to {status}")

def view_state(assignment_id):
    state = load_state(assignment_id)
    if not state:
        print(f"Error: Assignment {assignment_id} not found.")
        return
    print(json.dumps(state, indent=2))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="State Manager for OpenCode Swarm Assignments")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Init
    parser_init = subparsers.add_parser("init", help="Initialize a new assignment")
    parser_init.add_argument("assignment_id", help="Unique ID for the assignment")
    parser_init.add_argument("objective", help="Overall objective")

    # Add task
    parser_add = subparsers.add_parser("add_task", help="Add a task to an assignment")
    parser_add.add_argument("assignment_id", help="Assignment ID")
    parser_add.add_argument("task_id", help="Unique ID for the task")
    parser_add.add_argument("description", help="Task description")
    parser_add.add_argument("assigned_agent", help="Agent responsible for the task")
    parser_add.add_argument("--deps", help="Comma-separated list of dependent task IDs", default="")

    # Update task status
    parser_update = subparsers.add_parser("update_task", help="Update task status")
    parser_update.add_argument("assignment_id", help="Assignment ID")
    parser_update.add_argument("task_id", help="Task ID")
    parser_update.add_argument("status", help="New status (pending, in_progress, completed, failed)")
    parser_update.add_argument("--output", help="Path to output file generated by the task", default="")

    # Update assignment status
    parser_update_ass = subparsers.add_parser("update_assignment", help="Update overall assignment status")
    parser_update_ass.add_argument("assignment_id", help="Assignment ID")
    parser_update_ass.add_argument("status", help="New status (planning, in_progress, reviewing, completed)")

    # View state
    parser_view = subparsers.add_parser("view", help="View current state of an assignment")
    parser_view.add_argument("assignment_id", help="Assignment ID")

    args = parser.parse_args()

    if args.command == "init":
        init_assignment(args.assignment_id, args.objective)
    elif args.command == "add_task":
        add_task(args.assignment_id, args.task_id, args.description, args.assigned_agent, args.deps)
    elif args.command == "update_task":
        update_task_status(args.assignment_id, args.task_id, args.status, args.output)
    elif args.command == "update_assignment":
        update_assignment_status(args.assignment_id, args.status)
    elif args.command == "view":
        view_state(args.assignment_id)
